<?php
/**
 * Created by PhpStorm.
 * User: zach
 * Date: 2/2/16
 * Time: 4:23 PM
 */

namespace FS\SolrBundle\Doctrine\Annotation;


use Doctrine\Common\Annotations\Annotation;

/**
 * Class VirtualField
 *
 * @package FS\SolrBundle\Doctrine\Annotation
 *
 * @Annotation
 * @Target("METHOD")
 */
class VirtualField extends Field
{
    /**
     * @var string
     */
    public $alias;


    /**
     * {@inheritdoc}
     */
    public function getNameWithAlias()
    {
        if (!empty($this->alias)) {
            return $this->normalizeName($this->alias) . $this->getTypeSuffix($this->type);
        } else {
            return $this->normalizeName($this->name) . $this->getTypeSuffix($this->type);
        }
    }

    /**
     * {@inheritdoc}
     */
    protected function normalizeName($name)
    {
        if (strpos(strtolower($name), 'get') === 0) {
            $name   = lcfirst(substr($name, 3, strlen($name)));
        }

        return parent::normalizeName($name);
    }

    public function getValue()
    {
        return parent::getValue(); // TODO: Change the autogenerated stub
    }
}